### ISSUE TITLE
api compatibility with other ans1 library?

### ISSUE THREAD

**Issue by portno12** [andrivet/python-asn1#257]
there is this other asn1 library -> https://github.com/etingof/pyasn1 that only shows support to python 3.7 and has no updates since 2020, and no release since 2019. luckily this repo seems maintained and has kept up with python releases. the other library is packaged in some os but python has kept moving.

is this repo's code api compatible with it to allow for more maintained and updated code in the os packages, or will changes be needed in projects depending on it?

**Comment by andrivet** [comment]
>is this repo's code api compatible
No idea, I don't know this library.
