### ISSUE TITLE
Please Consider Update README

### ISSUE THREAD

**Issue by wxk6b1203** [andrivet/python-asn1#27]
Test platform: win10 x64

Reproduce: use sample code from readme

```py
import asn1

encoder = asn1.Encoder()
encoder.start()
encoder.write('1.2.3', asn1.ObjectIdentifier)
encoded_bytes = encoder.output()
```

As is runed from the latest branch master, `ObjectIdentifier` does not inside asn1, instead, in asn1.Numbers
Change
```py
encoder.write('1.2.3', asn1.ObjectIdentifier)
```
to
```py
encoder.write('1.2.3', asn1.Numbers.ObjectIdentifier)
```
![image](https://user-images.githubusercontent.com/8924149/65229869-88e90900-daff-11e9-9cf9-2ece3d01a1d0.png)

That works.

**Comment by andrivet** [comment]
Fixed, thanks for reporting this mistake.
