### ISSUE TITLE
New release would be great.

### ISSUE THREAD

**Issue by cmuellner** [andrivet/python-asn1#34]
v2.2.0 has been created in October 2017. Since then a couple of good patches have been merged, which deserve to be released after such a long time. Therefore a v2.2.1 or v2.3.0 would be nice.

**Comment by andrivet** [comment]
What are you talking about? You mean a release on PyPi?

**Comment by cmuellner** [comment]
A new git tag and an update of the pypi package (following that tag) would be nice.

**Comment by andrivet** [comment]
Will look at this. I have also the PR #17 pending (I have to write some unit test to be ready to merge it).

**Comment by andrivet** [comment]
New release 2.3.0 published today here and on Pypi. There are a few mistakes in the README, I will fix that later (unfortunately, I have to publish a new version to fix texts).
