### ISSUE TITLE
Convert the enums to actual enums

### ISSUE THREAD

**Issue by Powersource** [andrivet/python-asn1#8]
This would e.g. allow debugging using `print(Numbers(my_parsed_enum).name` and clean up at least my code significantly.

The caveat is that enums were added in 3.4 and to maintain backwards compatibility we'd have to use another package, [enum34](https://pypi.python.org/pypi/enum34/), does that sound ok?

**Comment by andrivet** [comment]
Implemented. Let me know if it is what you thought.

**Comment by Powersource** [comment]
I'm not using this anymore but I think it looks like what I had in mind 👍
