### ISSUE TITLE
The code is using (indirectly) enum.IntFlag which is not always defined.

### ISSUE THREAD

**Issue by andrivet** [andrivet/python-asn1#89]
Depending of the project using python-asn1, another `enum` module can be used (such as enum34) and will fail because it tries to use `IntFlag` introduced in Python 3.6.0.

This must be studied further (this is not the first problem with enum34) and the root cause fixed.

Related to:
* https://github.com/andrivet/python-asn1/issues/66
* https://github.com/andrivet/python-asn1/pull/86
* https://github.com/andrivet/python-asn1/pull/70

**Comment by c0dearm** [comment]
I have the exact same issue, I think `enum34` should only be used for Python < 3.4.

This line is doing the wrong check: https://github.com/andrivet/python-asn1/blob/74ce5c576f65cea26a52dd7b5a38102b6a287232/setup.py#L27

It is comparing the python major version only (3), so it is always using `enum34`, even for Python > 3.4

**Comment by andrivet** [comment]
This is why I am using in requirements.txt enum-compat. But I forgot to use it also in setup.py and in tox. I am currently testing a fix.

**Comment by andrivet** [comment]
Fixed in 2.4.1
