### ISSUE TITLE
Invalid negative integers encoding

### ISSUE THREAD

**Issue by stargrave** [andrivet/python-asn1#9]
Greetings!

I have noticed that big integer numbers are incorrectly encoded:

    for v in (
        -668929531791034950848739021124816874,
        -667441897913742713771034596334288035,
        -664674827807729028941298133900846368,
        -666811959353093594446621165172641478,
    ):
        encoder = asn1.Encoder()
        encoder.start()
        encoder.write(v, asn1.Numbers.Integer)
        encoded_bytes = encoder.output()
        decoder = asn1.Decoder()
        decoder.start(encoded_bytes)
        tag, value = decoder.read()
        if value != v:
            print(value, "!=", v)

The first examples produces the following binary value:

    020f7f2b3a4dea481e1f377ba8bd7fb016

but the correct one is following (that correctly decodes by your asn1 library):

    0210ff7f2b3a4dea481e1f377ba8bd7fb016
        ^^

**Comment by andrivet** [comment]
Thank you for reporting that. I will fix this bug when I find some time.

**Comment by andrivet** [comment]
Two's complement corner case with values such as -32769. Add also new test cases to test them.
